name: Build
on: [ push ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    # runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod -x .\gradlew.bat

      - name: Execute Gradle build
        run: .\gradlew shadowJar

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release Jar"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.TOKEN }}"
          files: |
            build/libs/*.jar
          prerelease: false
